### PR TITLE
Add some error handling and tupled results

### PR DESCRIPTION
**Pull request by jburnitz**
Removed extraneous imports
Set default dates if there is an null entry (unfilled)
Count how many are compliant and not

### CODE REVIEW

**Comment by jburnitz** [comment]
Note: custom Chicago calender needs implementation for more accurate results

**Comment by jburnitz** [comment]
realized business days weren't being counted correctly

**Comment by b-meson** [comment]
Thanks for the PR! I want to review the code a bit more closer before merging. The custom business calendar can be defined separately, its a small fix.

**Comment by jburnitz** [comment]
I did a quick rewrite to address the business days better. on line 32, when the date calculation is done, a custom list of holidays can be added in as an argument.

**Pull request merged**
